import { useState, useCallback } from 'react';
import type { VisualizerStep } from '../../types';

/**
 * Generic hook to manage visualizer state and playback.
 *
 * T – the type of the underlying data element (e.g. number for array/stack,
 *       a custom node type for trees, etc.).
 */
export function useVisualizer<T>() {
  // underlying data structure values
  const [data, setData] = useState<T[]>([]);

  // playback steps generated by operation handlers
  const [steps, setSteps] = useState<VisualizerStep[]>([]);
  const [currentStepIndex, setCurrentStepIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [speed, setSpeed] = useState(800); // ms per step, can be tuned by UI

  /** Reset visualizer with a fresh data set and an initial explanatory step */
  const reset = useCallback((initialData: T[], message: string) => {
    setData(initialData);
    setSteps([
      {
        stepNumber: 1,
        explanation: message,
        // generic state – visualizer components can extend it as needed
        // we spread the data so each component sees a copy
        state: { data: [...initialData] } as any,
      },
    ]);
    setCurrentStepIndex(0);
    setIsPlaying(false);
  }, []);

  /** Append new steps produced by an operation */
  const addSteps = useCallback((newSteps: VisualizerStep[]) => {
    setSteps(prev => [...prev, ...newSteps]);
    // reset playback to start of new steps
    setCurrentStepIndex(0);
    setIsPlaying(true);
  }, []);

  /** Playback controls */
  const play = useCallback(() => setIsPlaying(true), []);
  const pause = useCallback(() => setIsPlaying(false), []);
  const next = useCallback(() => {
    setCurrentStepIndex(prev => Math.min(steps.length - 1, prev + 1));
  }, [steps.length]);
  const prev = useCallback(() => {
    setCurrentStepIndex(prev => Math.max(0, prev - 1));
  }, []);
  const resetPlayback = useCallback(() => {
    setCurrentStepIndex(0);
    setIsPlaying(false);
  }, []);

  return {
    data,
    setData,
    steps,
    setSteps,
    currentStepIndex,
    setCurrentStepIndex,
    isPlaying,
    setIsPlaying,
    speed,
    setSpeed,
    reset,
    addSteps,
    play,
    pause,
    next,
    prev,
    resetPlayback,
  } as const;
}
